### ISSUE TITLE
Improve automation of release procedure

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-sphinx#27]
# The current features of the release job are:

- Create a python package
- Upload the package to pypi

# Desired features:

- Add date to changelog before release
- Add version tag in Git
- Execute version bump after release
- Add new section to changelog after release

**Comment by wouterdb** [comment]
@arnaudsjs This could do with a bit more description to make it actionable.

**Comment by arnaudsjs** [comment]
The current features of the release job are:
* Create a python package
* Upload the package to pypi

Desired features:
* Add date to changelog before release
* Add version tag in Git
* Execute version bump after release
* Add new section to changelog after release

**Comment by sanderr** [comment]
@arnaudsjs does this refer to [this Jenkins job](https://jenkins.inmanta.com/job/releases/job/python-packages/job/sphinx-inmanta-pypi-release/)? Is there a Jenkinsfile in version control, or should it be updated via the Jenkins UI?

**Comment by arnaudsjs** [comment]
> @arnaudsjs does this refer to [this Jenkins job](https://jenkins.inmanta.com/job/releases/job/python-packages/job/sphinx-inmanta-pypi-release/)? Is there a Jenkinsfile in version control, or should it be updated via the Jenkins UI?

Yes. And there is also the job to create a [dev release](https://jenkins.inmanta.com/job/releases/job/python-packages/job/sphinx-inmanta-pypi-dev-release/configure). Both don't have a Jenksinsfile, so configuration has to happen via the UI. But don't hesitate to create a Jenkinsfile if you would like to create one.
