### ISSUE TITLE
Sphinx should support all module classes

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-sphinx#46]
We use the Module class from core. This class is split into modules v1/v2 versions. This breaks this extension. https://github.com/inmanta/inmanta-sphinx/pull/45 fixes it (in an ugly way). We need to handle this in a proper manner, including adding v2 support to sphinx.

**Comment by wouterdb** [comment]
use proper method to construct module, timebox

**Comment by sanderr** [comment]
`Module.from_path` does exactly this.
