### ISSUE TITLE
Pygments Lexer breaks on valid inmanta models

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-sphinx#51]
The lexer fails to parse inmanta models where an entity contains an attribute of type `string[]?`. This causes issues for code snippets where embedded entities set the `string[]? __lsm_key_attributes` attribute. The result is that these code block do not get the inmanta syntax highlighting in the documentation.

The above-mentioned in issue exists for the file: *docs/moduleguides/lsm/embedded_entities/embedded_entities_sources/example_key_attributes.cf*. But similar issue may exists in other places. Related warnings found in the output of the ISO documentation build:

```
docs/moduleguides/lsm/allocation/allocation.rst:39: WARNING: Could not lex literal_block as "inmanta". Highlighting skipped.
docs/moduleguides/lsm/allocation/allocation.rst:88: WARNING: Could not lex literal_block as "inmanta". Highlighting skipped.
docs/moduleguides/lsm/allocation/allocation.rst:157: WARNING: Could not lex literal_block as "inmanta". Highlighting skipped.
docs/moduleguides/lsm/allocation/allocation_v2.rst:19: WARNING: Could not lex literal_block as "inmanta". Highlighting skipped.
docs/moduleguides/lsm/allocation/allocation_v2.rst:107: WARNING: Could not lex literal_block as "inmanta". Highlighting skipped.
docs/moduleguides/lsm/allocation/allocation_v2.rst:140: WARNING: Could not lex literal_block as "inmanta". Highlighting skipped.
docs/moduleguides/lsm/embedded_entities/embedded_entities.rst:126: WARNING: Could not lex literal_block as "inmanta". Highlighting skipped.
```

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-sphinx/51?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta
