### ISSUE TITLE
Module documentation renders in a weird way

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-sphinx#71]
Example: https://docs.inmanta.com/inmanta-service-orchestrator-dev/8/reference/modules/aci.html#aci.resources.StandaloneProvider

* ~~The handler name is rendered as ````. This happens because the handler doesn't set a name, because there is only one handler for multiple resources.~~
* The same handler class is displayed multiple times in the documentation.

Related Slack discussion: https://inmanta.slack.com/archives/CKRF0C8R3/p1721380143263339

**Comment by sanderr** [comment]
discussed in planning meeting:
1. ~~for the ```` issue, double check whether the name is not set + check with solutions team if we should allow it to be absent (it's currently typed `str`, not `Optional[str]`).~~
2. The same handler class is displayed multiple times because we reuse the same class for multiple resources (stacked `@provider`). This should be displayed correctly. Investigate what is easiest.
3. ~~The generated documentation may be meaningless in the first place, given that we will soon be able to use the `README.md` to drive the docs. Check with the solutions team how relevant this ticket is (if we wouldn't ever generate it for these modules, it's not that meaningful).~~

**Comment by sanderr** [comment]
Assigning to @hlloreda to check on point 3.

**Comment by hlloreda** [comment]
Point 1 seems to have disappeared. But point 2 is still relevant when it comes to generic handlers, so we should take action on this (this part of the documentation is still used).
